# render.yaml (Minimal version to bypass errors)

databases:
  - name: my-postgres-db
    plan: free

services:
  - type: redis
    name: my-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0

  - type: web
    name: django-web-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn homeo_expert_ai.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.12

  - type: worker
    name: celery-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A homeo_expert_ai worker --loglevel=info"
    envVars:
      - fromService: # This links the SECRET_KEY from the web service
          type: web
          name: django-web-app
          envVarKey: SECRET_KEY
      - key: PYTHON_VERSION
        value: 3.10.12