databases:
  - name: my-postgres-db
    plan: free

services:
  - type: redis
    name: my-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0

  - type: web
    name: django-celery-app
    plan: free
    env: docker # IMPORTANT: We tell Render to use our Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: my-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false # Set this manually in the dashboard
      - key: PYTHON_VERSION
        value: 3.10.12