# Generated by Django 5.2 on 2025-04-17 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opd_no', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.CharField(max_length=20)),
                ('patient_sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('patient_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('presenting_complaints', models.TextField()),
                ('history_of_present_illness', models.TextField(blank=True, null=True)),
                ('past_history_vaccination', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('personal_history', models.JSONField(blank=True, default=dict, null=True)),
                ('menstrual_history', models.JSONField(blank=True, default=dict, null=True)),
                ('physical_examination', models.JSONField(blank=True, default=dict, null=True)),
                ('patient_as_person', models.TextField(blank=True, null=True)),
                ('systemic_examination', models.TextField(blank=True, null=True)),
                ('analysis_evaluation', models.JSONField(blank=True, null=True)),
                ('repertorization', models.JSONField(blank=True, null=True)),
                ('potential_remedies', models.JSONField(blank=True, null=True)),
                ('prescription', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Analysis'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PastIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, max_length=200, null=True)),
                ('approximate_age', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('completely_recovered', models.CharField(blank=True, max_length=50, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_illnesses', to='core.case')),
            ],
            options={
                'verbose_name_plural': 'Past Illnesses',
            },
        ),
    ]
