# Generated by Django 5.2 on 2025-04-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_case_analysis_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='opd_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
